services:
  postgres_db:
    image: postgres:18.1-alpine
    container_name: java_postgres_container
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vehicle_renting
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s

  minio:
    image: minio/minio:latest
    container_name: minio_c
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=dev-access-key
      - MINIO_ROOT_PASSWORD=dev-secret-key
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  postgres_data:

