spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5430}/${POSTGRES_DB:vehicle_renting}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:secret}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


logging:
  level:
    root: info
    org.flywaydb: DEBUG

jwt.secret: ${JWT_SECRET:mydevsecretkey}

aws.s3:
  bucket-name: ${AWS_S3_BUCKET:vehicleimages}
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY:dev-access-key}
  secret-key: ${AWS_SECRET_KEY:dev-secret-key}
  endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}